version: '3.8'

services:
  proxy-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGET: proxy-server
    container_name: proxy-server
    ports:
      - "9000:9000"
    volumes:
      - ./config/proxy-config.json:/app/config.json
      - ./data/proxy:/app/data
    restart: always
    extra_hosts:
      - "server-1:127.0.0.1"
      - "server-2:127.0.0.1"

  server-1:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGET: server-1
    container_name: server-1
    ports:
      - "9101:9101"
    volumes:
      - ./config/server-1-config.json:/app/config.json
      - ./data/server1:/app/data
    restart: always
    hostname: server-1

  server-2:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGET: server-2
    container_name: server-2
    ports:
      - "9102:9102"
    volumes:
      - ./config/server-2-config.json:/app/config.json
      - ./data/server2:/app/data
    restart: always
    hostname: server-2

  backup-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGET: backup-server
    container_name: backup-server
    volumes:
      - ./config/backup-config.json:/app/config.json
      - ./data/backup:/app/data
    restart: always
    extra_hosts:
      - "server-1:127.0.0.1"
      - "server-2:127.0.0.1"
