version: '3.8'

services:
  proxy-server:
    build:
      context: .
      dockerfile: cmd/proxy-server/Dockerfile
    container_name: proxy-server
    ports:
      - "9000:9000" 
    volumes:
      - ./config/proxy-config.json:/app/config.json
      - ./data/proxy:/app/data
    restart: always

  server-1:
    build:
      context: .
      dockerfile: cmd/server-1/Dockerfile
    container_name: server-1
    ports:
      - "9101:9101"
    volumes:
      - ./config/server-1-config.json:/app/config.json
      - ./data/server1:/app/data
    restart: always

  server-2:
    build:
      context: .
      dockerfile: cmd/server-2/Dockerfile
    container_name: server-2
    ports:
      - "9102:9102"
    volumes:
      - ./config/server-2-config.json:/app/config.json
      - ./data/server2:/app/data
    restart: always

  backup-server:
    build:
      context: .
      dockerfile: cmd/backup-server/Dockerfile
    container_name: backup-server
    ports:
      - "9103:9103"
    volumes:
      - ./config/backup-config.json:/app/config.json
      - ./data/backup:/app/data
    restart: always
